# Generated by Django 5.2.12 on 2026-03-27 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niche_app', '0005_niche_current_round'),
        ('publish_app', '0001_initial'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTrash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_designs', to=settings.AUTH_USER_MODEL)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trash_record', to='publish_app.designasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_trash', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name_plural': 'Design trash',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='NicheComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(blank=True, default='', help_text='Agent type for agent comments (e.g. orchestrator, research)', max_length=50)),
                ('content', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list, help_text='List of mentioned user IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, help_text='Null for agent-generated comments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niche_comments', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, help_text='Null = card-level comment; set = design-level comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publish_app.designasset')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='niche_app.niche')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['niche', 'design'], name='comment_niche_design_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('assignment', 'Assignment'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('mention', 'Mention'), ('status_change', 'Status Change'), ('agent_action', 'Agent Action')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', help_text='Deep link path to card/design (e.g. /kanban?card=<uuid>)', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('source_agent_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_read_idx'), models.Index(fields=['workspace', 'recipient'], name='notif_ws_recipient_idx')],
            },
        ),
    ]
