# Generated by Django 5.1.7 on 2026-03-14 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(db_index=True, max_length=20)),
                ('marketplace', models.CharField(choices=[('amazon_com', 'Amazon.com (US)'), ('amazon_de', 'Amazon.de (DE)'), ('amazon_co_uk', 'Amazon.co.uk (UK)'), ('amazon_fr', 'Amazon.fr (FR)'), ('amazon_it', 'Amazon.it (IT)'), ('amazon_es', 'Amazon.es (ES)')], db_index=True, max_length=20)),
                ('title', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('bsr', models.IntegerField(blank=True, db_index=True, null=True)),
                ('bsr_categories', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('subcategory', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('listed_date', models.DateField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('t_shirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('pullover', 'Pullover'), ('zip_hoodie', 'Zip Hoodie'), ('long_sleeve', 'Long Sleeve'), ('tank_top', 'Tank Top'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=2048)),
                ('product_url', models.URLField(blank=True, default='', max_length=2048)),
                ('seller_name', models.CharField(blank=True, default='', max_length=200)),
                ('feature_bullets', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('image_gallery', models.JSONField(blank=True, default=list)),
                ('scraped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bsr_min', models.IntegerField()),
                ('bsr_max', models.IntegerField(blank=True, null=True)),
                ('interval_days', models.IntegerField()),
            ],
            options={
                'ordering': ['bsr_min'],
            },
        ),
        migrations.CreateModel(
            name='BSRSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bsr', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsr_snapshots', to='scraper_app.amazonproduct')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_index=True, max_length=200)),
                ('marketplace', models.CharField(choices=[('amazon_com', 'Amazon.com (US)'), ('amazon_de', 'Amazon.de (DE)'), ('amazon_co_uk', 'Amazon.co.uk (UK)'), ('amazon_fr', 'Amazon.fr (FR)'), ('amazon_it', 'Amazon.it (IT)'), ('amazon_es', 'Amazon.es (ES)')], db_index=True, max_length=20)),
            ],
            options={
                'unique_together': {('keyword', 'marketplace')},
            },
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='products', to='scraper_app.keyword'),
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('live', 'Live Research'), ('scheduled', 'Scheduled Scrape'), ('bsr_snapshot', 'BSR Snapshot')], db_index=True, max_length=20)),
                ('asin', models.CharField(blank=True, default='', max_length=20)),
                ('marketplace', models.CharField(choices=[('amazon_com', 'Amazon.com (US)'), ('amazon_de', 'Amazon.de (DE)'), ('amazon_co_uk', 'Amazon.co.uk (UK)'), ('amazon_fr', 'Amazon.fr (FR)'), ('amazon_it', 'Amazon.it (IT)'), ('amazon_es', 'Amazon.es (ES)')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('pages_total', models.IntegerField(default=4)),
                ('pages_done', models.IntegerField(default=0)),
                ('products_scraped', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User')], max_length=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rq_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_jobs', to='scraper_app.keyword')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSearchCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_caches', to='scraper_app.keyword')),
                ('scrape_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_caches', to='scraper_app.scrapejob')),
            ],
            options={
                'verbose_name_plural': 'Product search caches',
            },
        ),
        migrations.CreateModel(
            name='ScheduledScrapeTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('marketplace', models.CharField(choices=[('amazon_com', 'Amazon.com (US)'), ('amazon_de', 'Amazon.de (DE)'), ('amazon_co_uk', 'Amazon.co.uk (UK)'), ('amazon_fr', 'Amazon.fr (FR)'), ('amazon_it', 'Amazon.it (IT)'), ('amazon_es', 'Amazon.es (ES)')], db_index=True, max_length=20)),
                ('tier_override', models.BooleanField(default=False)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('next_scrape_at', models.DateTimeField(db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_targets', to='scraper_app.keyword')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='scraper_app.scrapetier')),
            ],
            options={
                'ordering': ['next_scrape_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='amazonproduct',
            unique_together={('asin', 'marketplace')},
        ),
    ]
