# Generated by Django 5.1.7 on 2026-03-16 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0004_replace_feature_bullets_with_bullet_1_bullet_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='mode',
            field=models.CharField(choices=[('live', 'Live Research'), ('scheduled', 'Scheduled Scrape'), ('bsr_snapshot', 'BSR Snapshot'), ('search_page_only', 'Search Page Only')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MetaKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(choices=[('short_tail', 'Short Tail'), ('long_tail', 'Long Tail')], db_index=True, max_length=20)),
                ('frequency', models.IntegerField(default=0)),
                ('search_keywords', models.ManyToManyField(blank=True, related_name='meta_keywords', to='scraper_app.keyword')),
            ],
            options={
                'unique_together': {('keyword', 'type')},
            },
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, related_name='products', to='scraper_app.metakeyword'),
        ),
        migrations.CreateModel(
            name='SearchKeywordResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_focus_keywords', models.JSONField(blank=True, default=list)),
                ('top_long_tail_keywords', models.JSONField(blank=True, default=list)),
                ('all_keywords_flat', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_cache', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_result', to='scraper_app.productsearchcache')),
            ],
        ),
    ]
