# Generated by Django 5.2.12 on 2026-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0005_alter_scrapejob_mode_metakeyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand Blacklist',
                'verbose_name_plural': 'Brand Blacklist',
                'ordering': ['brand_name'],
            },
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='pages_total',
            field=models.IntegerField(default=2),
        ),
    ]
