"""Seed BrandBlacklist with ~480 trademarked brands from n8n workflow."""

from django.db import migrations


BRANDS = [
    "20th century studios", "7up", "absolut", "ac/dc", "activision blizzard",
    "adidas", "adult swim / warner bros.", "adventure time", "alice in wonderland",
    "american dad", "alien", "amc", "among us", "aniplex", "apex legends",
    "apple", "apple corps", "anheuser-busch", "assassin's creed",
    "attack on titan", "audi", "authentic brands group",
    "avatar: the last airbender", "avengers", "bandai", "bandai namco",
    "bandai namco filmworks", "barbie", "barney & friends", "batman", "bbc",
    "bayern munich", "ben 10", "betty boop", "big bird", "big hero 6",
    "blackpink", "blade runner", "blizzard entertainment", "blue's clues",
    "bluey", "bluestar alliance", "bmw", "bmw group", "bones",
    "boston celtics", "boston red sox", "breaking bad", "brooklyn nets", "bts",
    "budweiser", "bugs bunny", "bundesliga", "burger king", "call of duty",
    "calvin klein", "capcom", "captain america", "care bears", "carlsberg",
    "cars", "cartoon network", "casper", "castlevania", "caterpillar",
    "chainsaw man", "champion", "chanel", "charlie brown", "cheetos",
    "chevrolet", "chicago bears", "chicago bulls", "chococat", "cinnamoroll",
    "cloudco entertainment", "coca-cola", "coco", "columbia pictures",
    "comedy central", "converse", "cookie monster", "coors", "corona",
    "corvette", "costco", "counter-strike", "cowboy bebop", "crunchyroll",
    "curious", "cutecomfy", "george", "cyberpunk 2077", "dallas cowboys",
    "dark souls", "dc comics", "demon slayer", "despicable me", "destiny",
    "diego", "disneyland", "disney", "disney parks", "disney pixar",
    "disney princess", "doctor who", "dodge", "dora the explorer", "doritos",
    "dota 2", "dotdash meredith", "dragon ball", "dreamworks",
    "dreamworks animation", "dr pepper", "dune", "dunkin'", "ea sports",
    "elden ring", "elmo", "elvis presley", "encanto", "epic games", "espn",
    "e.t.", "facebook", "fairy tail", "family guy", "fanta",
    "fantastic beasts", "fast & furious", "fc barcelona", "felix the cat",
    "ferrari", "fifa", "fifa (game)", "figma", "fila", "final fantasy",
    "fisher-price", "five nights at freddy's", "ford", "formula 1",
    "fortnite", "friends", "fender", "fromsoft", "fromsoftware", "frozen",
    "funimation", "funko", "funko pop", "fx networks", "game of thrones",
    "garfield", "gatorade", "gears of war", "ghostbusters", "g.i. joe",
    "golden state warriors", "good smile company", "goonies", "google",
    "gordon brothers", "grand theft auto", "green bay packers", "gta",
    "gucci", "guinness", "guns n' roses", "h&m", "halo", "hanna-barbera",
    "harley quinn", "harley-davidson", "harry potter", "hasbro", "hatchimals",
    "hbo", "hbo / warner bros.", "heineken", "hello kitty", "he-man",
    "henry danger", "hershey's", "honda", "hot toys", "hot wheels",
    "house of the dragon", "how to train your dragon", "icarly", "ice age",
    "ikea", "illumination", "imps", "indiana jones", "innersloth", "instagram",
    "iron man", "jack daniel's", "james bond", "jaws", "jazwares", "jeep",
    "johnnie walker", "john deere", "joker", "jujutsu kaisen", "jurassic park",
    "jurassic world", "justice league", "kansas city chiefs", "kellogg's",
    "keroppi", "kfc", "kingdom hearts", "kit kat", "kodansha", "konami",
    "krispy kreme", "kung fu panda", "kuromi", "kyoto animation", "la liga",
    "lady gaga", "lamborghini", "las vegas raiders", "lay's",
    "league of legends", "led zeppelin", "legendary entertainment", "lego",
    "lego harry potter", "lego marvel", "lego star wars", "lego technic",
    "levi's", "levi strauss & co.", "ligue 1", "lilo & stitch",
    "littlest pet shop", "liverpool fc", "l.o.l. surprise", "looney tunes",
    "los angeles dodgers", "los angeles lakers", "louis vuitton", "louvre",
    "lucasfilm / disney", "luigi", "madden nfl", "madagascar", "madhouse",
    "major league baseball", "manchester united", "mappa", "mario", "marvel",
    "masters of the universe", "mattel", "mazda", "mcdonald's",
    "medicom toy", "men in black", "mercedes-benz", "meta",
    "metal gear solid", "metallica", "mga entertainment", "miami heat",
    "michael jackson", "michael jackson estate", "mickey mouse", "microsoft",
    "motomotive ink", "miffy", "miller", "minecraft", "minions",
    "minnie mouse", "mission: impossible", "m&m's", "moana", "mojang",
    "mojang / microsoft", "moma", "monster beverage", "monster energy",
    "monster hunter", "monopoly", "moomin", "mortal kombat",
    "mr. men little miss", "mtv", "mustang", "my hero academia",
    "my little pony", "my melody", "naruto", "nasa", "nascar",
    "national basketball association", "national football league",
    "national geographic", "national hockey league", "nba", "nbcuniversal",
    "nbpa", "nendoroid", "nerf", "nestl\u00e9", "netflix", "netflix originals",
    "new balance", "new england patriots", "new york giants",
    "new york yankees", "nfl", "nfl players association", "nflpa", "nhl",
    "nickelodeon", "nike", "nike inc.", "nintendo", "nissan", "one piece",
    "olympics", "olympic games", "oreo", "overwatch",
    "paddington and company", "paddington bear", "pack a punch", "paramount",
    "paramount+", "patagonia", "paw patrol", "paws", "peanuts", "pewpew",
    "pew pew", "peanuts worldwide", "people inc.", "peppa pig", "pepsi",
    "pepsi-cola", "pepsico", "philadelphia eagles", "pink floyd",
    "pink panther", "pittsburgh steelers", "pixar", "pizza hut", "playboy",
    "playboy enterprises", "playskool", "playmobil", "play-doh", "pokemon",
    "pok\u00e9mon", "polly pocket", "popeye", "porsche", "porsche ag",
    "power rangers", "power rangers franchise", "prada", "predator",
    "premier league", "primark", "pringles", "production i.g", "puma",
    "queen", "ralph lauren", "ravensburger", "real madrid", "red bull",
    "reebok", "reese's", "regular show", "resident evil", "revell",
    "rick and morty", "riot games", "robocop", "roblox",
    "roblox corporation", "rockstar games", "rolling stones", "rugrats",
    "samsung", "sanrio", "schleich", "scooby-doo", "scott cawthon",
    "sea world", "sega", "sesame street", "sesame street characters",
    "sesame workshop", "shonen jump", "shopkins", "shrek", "shueisha",
    "shueisha / toho", "shueisha / toei animation",
    "shueisha / tv tokyo", "silent hill", "simpsons", "six flags",
    "skittles", "smirnoff", "smithsonian", "smurfs", "snapchat", "snickers",
    "snoopy", "sonic the hedgehog", "sony interactive entertainment",
    "sony pictures", "south park", "spider-man",
    "spin master / nickelodeon", "spongebob squarepants", "sports wwe",
    "sprite", "spy x family", "squid game", "square enix", "starbucks",
    "star trek", "star wars", "steam", "steven universe", "stranger things",
    "street fighter", "studio ghibli", "subaru", "subway",
    "super mario bros", "superman", "supreme", "taco bell",
    "tamashii nations", "tamiya", "target", "taylor swift",
    "teenage mutant ninja turtles", "teletubbies", "terminator", "tesla",
    "the beatles", "the coca-cola company", "the flash", "the flintstones",
    "the hobbit", "the jetsons", "the last of us", "the little mermaid",
    "the lord of the rings", "the mandalorian", "the matrix", "the met",
    "the muppets", "the north face", "the pink panther",
    "the pokemon company", "the pok\u00e9mon company international",
    "the powerpuff girls", "the simpsons", "the smurfs", "the walking dead",
    "the witcher", "the witcher (netflix)", "thomas & friends", "tiktok",
    "tko group", "tmnt", "toei animation", "toei animation / shueisha",
    "tokyo disney", "tokyo ghoul", "tom and jerry", "tommy hilfiger", "tonka",
    "top gun", "toyota", "toy story", "transformers", "trigger", "trolls",
    "twilight", "twix", "twitter", "ubisoft", "uefa",
    "uefa champions league", "ufc", "under armour", "uniqlo", "universal",
    "universal / illumination", "universal pictures", "universal studios",
    "uno", "valve", "valorant", "vans", "vh1", "volkswagen", "walmart",
    "warner bros.", "warner bros. / wizarding world",
    "warner bros. discovery", "wednesday", "wendy's", "winnie the pooh",
    "wit studio", "wizarding world", "wonder woman", "world of warcraft",
    "wreck-it ralph", "wwe", "wwe raw", "wwe smackdown", "x", "xbox",
    "x-men", "yo gabba gabba", "yum! brands", "zara", "zelda",
]


def seed_brands(apps, schema_editor):
    BrandBlacklist = apps.get_model('scraper_app', 'BrandBlacklist')
    objs = [BrandBlacklist(brand_name=name.strip()) for name in BRANDS]
    BrandBlacklist.objects.bulk_create(objs, ignore_conflicts=True)


def unseed_brands(apps, schema_editor):
    BrandBlacklist = apps.get_model('scraper_app', 'BrandBlacklist')
    BrandBlacklist.objects.filter(brand_name__in=[n.strip() for n in BRANDS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0006_brand_blacklist'),
    ]

    operations = [
        migrations.RunPython(seed_brands, unseed_brands),
    ]
