# Generated by Django 5.2.12 on 2026-03-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0007_amazonproduct_fts_gin_index'),
        ('scraper_app', '0007_seed_brand_blacklist'),
    ]

    operations = [
    ]
