# Generated by Django 5.2.12 on 2026-03-29 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0008_merge_20260322_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearchcache',
            name='browse_node',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productsearchcache',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsearchcache',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsearchcache',
            name='sort_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='browse_node',
            field=models.CharField(blank=True, default='', help_text='Amazon browse node ID for category filtering', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price filter (USD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price filter (USD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='sort_by',
            field=models.CharField(blank=True, choices=[('', 'Relevance'), ('exact-aware-popularity-rank', 'Best Sellers'), ('featured-rank', 'Featured'), ('date-desc-rank', 'Newest Arrivals'), ('price-asc-rank', 'Price: Low to High'), ('price-desc-rank', 'Price: High to Low'), ('review-rank', 'Avg. Customer Review')], default='', help_text='Amazon search sort parameter', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='pages_total',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
