# Generated by Django 5.2.12 on 2026-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0009_sort_filter_browse_node_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='product_type',
            field=models.CharField(choices=[('t_shirt', 'T-Shirt (Standard)'), ('premium_shirt', 'Premium Shirt'), ('comfort_colors', 'Comfort Colors'), ('v_neck', 'V-Neck'), ('long_sleeve', 'Long Sleeve'), ('raglan', 'Raglan'), ('sweatshirt', 'Sweatshirt'), ('hoodie', 'Hoodie'), ('performance_polo', 'Performance Polo'), ('zip_hoodie', 'Zip Hoodie'), ('popsocket', 'PopSocket'), ('phone_case', 'Phone Case'), ('tote_bag', 'Tote Bag'), ('tumbler', 'Tumbler'), ('ceramic_mug', 'Ceramic Mug'), ('tank_top', 'Tank Top'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='product_type_filter',
            field=models.CharField(blank=True, choices=[('', 'All Products (no filter)'), ('t_shirt', 'T-Shirt (Standard)'), ('premium_shirt', 'Premium Shirt'), ('comfort_colors', 'Comfort Colors'), ('v_neck', 'V-Neck'), ('long_sleeve', 'Long Sleeve'), ('raglan', 'Raglan'), ('sweatshirt', 'Sweatshirt'), ('hoodie', 'Hoodie'), ('performance_polo', 'Performance Polo'), ('zip_hoodie', 'Zip Hoodie'), ('popsocket', 'PopSocket'), ('phone_case', 'Phone Case'), ('tote_bag', 'Tote Bag'), ('tumbler', 'Tumbler'), ('ceramic_mug', 'Ceramic Mug'), ('tank_top', 'Tank Top')], default='', help_text='Filter Amazon search to specific MBA product type', max_length=20),
        ),
    ]
