# Generated by Django 5.2.12 on 2026-03-29 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0010_alter_amazonproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='start_page',
            field=models.PositiveIntegerField(default=1, help_text='First search result page to scrape (default: 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
