# Generated by Django 5.2.12 on 2026-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0011_add_start_page_to_scrapejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsearchcache',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
