# Generated by Django 5.2.12 on 2026-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0012_add_cancelled_status_to_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearchcache',
            name='product_type_filter',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
