# Generated by Django 5.2.12 on 2026-03-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0013_add_product_type_filter_to_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='prompt_analysis',
            field=models.JSONField(blank=True, default=None, help_text='Gemini 3 Architect 7-step image analysis output', null=True),
        ),
    ]
