# Generated by Django 5.2.13 on 2026-05-01 07:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0014_amazonproduct_prompt_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanaryAsin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(help_text='10-char Amazon ASIN (uppercase alphanumeric).', max_length=10, validators=[django.core.validators.RegexValidator(message='ASIN must be exactly 10 uppercase alphanumeric characters.', regex='^[A-Z0-9]{10}$')])),
                ('marketplace', models.CharField(choices=[('amazon_com', 'Amazon.com (US)'), ('amazon_de', 'Amazon.de (DE)'), ('amazon_co_uk', 'Amazon.co.uk (UK)'), ('amazon_fr', 'Amazon.fr (FR)'), ('amazon_it', 'Amazon.it (IT)'), ('amazon_es', 'Amazon.es (ES)')], db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text='Free text label, e.g. "MBA T-Shirt EN with BSR".', max_length=200)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Inactive canaries are skipped by the weekly scheduler.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canary ASIN',
                'verbose_name_plural': 'Canary ASINs',
                'ordering': ['marketplace', 'asin'],
                'unique_together': {('asin', 'marketplace')},
            },
        ),
        migrations.CreateModel(
            name='SelectorHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('html_path', models.TextField(blank=True, help_text='Path relative to MEDIA_ROOT; nulled when snapshot is pruned.', null=True)),
                ('html_size_bytes', models.IntegerField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict, help_text='{"title": "OK", "brand": "OK", "bsr": "INFO", ...}')),
                ('passed', models.BooleanField(db_index=True, default=False, help_text='True iff zero EMPTY entries in results.')),
                ('triggered_by', models.CharField(choices=[('schedule', 'Schedule'), ('admin', 'Admin'), ('cli', 'CLI')], db_index=True, default='schedule', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated on spider/HTTP failure.', null=True)),
                ('canary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='scraper_app.canaryasin')),
            ],
            options={
                'verbose_name': 'Selector Health Check',
                'verbose_name_plural': 'Selector Health Checks',
                'ordering': ['-run_at'],
            },
        ),
    ]
