# Generated by Django 5.2.13 on 2026-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0015_canary_asin_and_health_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='False once Amazon serves the Sorry/Dogs-of-Amazon page for this ASIN.'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='unavailable_since',
            field=models.DateTimeField(blank=True, db_index=True, help_text='First time we detected the product as unavailable. Stable across re-scrapes; cleared on recovery.', null=True),
        ),
    ]
