# Generated by Django 5.2.13 on 2026-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0016_amazonproduct_unavailable_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrent_requests', models.PositiveIntegerField(default=40, help_text='Scrapy CONCURRENT_REQUESTS — global concurrent downloader slots.')),
                ('concurrent_requests_per_domain', models.PositiveIntegerField(default=40, help_text='Scrapy CONCURRENT_REQUESTS_PER_DOMAIN — usually equal to CONCURRENT_REQUESTS for amazon.*.')),
                ('download_delay_ms', models.PositiveIntegerField(default=0, help_text='Scrapy DOWNLOAD_DELAY in milliseconds (converted to seconds at spawn).')),
            ],
            options={
                'verbose_name': 'Scraper Config',
                'verbose_name_plural': 'Scraper Config',
            },
        ),
    ]
