# Generated by Django 5.2.13 on 2026-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0019_scraperconfig_batch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearchcache',
            name='pages_scraped_at',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
