# Generated by Django 5.2.13 on 2026-05-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0024_scrapejob_extra_rh_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='extra_rh_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional Amazon `rh=` query refinements as flat key:value JSON object. Each entry becomes a `key:value` pair in the comma-separated `rh=` URL parameter. Examples: {"p_76": "2661625011"} (Prime/shipping filter), {"p_n_g-101015233022111": "121075132011"} (genre refinement), {"n": "7147445011"} (department node refinement). The built-in seller_filter (p_6) from product_type_filter is merged in automatically; do not duplicate it here.', null=True),
        ),
    ]
