services:
  db:
    image: postgres:16-alpine
    container_name: app_database
    env_file: ./django-app/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: app_redis
    restart: unless-stopped

  worker:
    build:
      context: ./django-app
      dockerfile: backend.Dockerfile
    container_name: app_worker
    entrypoint: ["./worker.entrypoint.sh"]
    command: python manage.py rqworker default
    env_file: ./django-app/.env
    restart: unless-stopped
    depends_on:
      - db
      - redis

  web:
    build:
      context: ./django-app
      dockerfile: backend.Dockerfile
    container_name: app_backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./django-app/.env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend-ui
      dockerfile: Dockerfile
      target: dev
    container_name: app_frontend
    depends_on:
      - web

volumes:
  postgres_data:
