# Generated by Django 5.2.12 on 2026-03-27 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niche_app', '0005_niche_current_round'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='idle', max_length=20)),
                ('workflow_template', models.CharField(blank=True, default='', max_length=50)),
                ('autonomy_preset', models.CharField(default='assisted', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('current_step', models.CharField(blank=True, default='', max_length=100)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('niche_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='niche_app.niche')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System'), ('approval_request', 'Approval Request'), ('approval_response', 'Approval Response')], max_length=20)),
                ('content', models.TextField()),
                ('agent_type', models.CharField(blank=True, default='', max_length=50)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_app.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(max_length=50)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_object_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='started', max_length=20)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action_logs', to='workspace_app.workspace')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='agent_app.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutonomyPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=dict, help_text='{tool_name: permission_level} mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autonomy_presets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomy_presets', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown content')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('chat_command', 'Chat Command'), ('auto_extracted', 'Auto Extracted')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('permission_level', models.CharField(choices=[('auto', 'Auto'), ('notify', 'Notify'), ('approve', 'Approve')], default='auto', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_permissions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_permissions', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name': 'Tool Permission',
                'verbose_name_plural': 'Tool Permissions',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(db_index=True, max_length=50)),
                ('is_system', models.BooleanField(default=False)),
                ('steps', models.JSONField(default=list, help_text='Ordered list of {agent_type, action, description}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('orchestrator', 'Orchestrator'), ('research', 'Research'), ('ideation', 'Ideation'), ('design', 'Design'), ('listing', 'Listing'), ('publishing', 'Publishing'), ('search', 'Search')], db_index=True, max_length=20)),
                ('display_name', models.CharField(max_length=50)),
                ('personality', models.TextField(blank=True, default='', help_text='Custom personality injected into system prompt')),
                ('avatar_emoji', models.CharField(default='🤖', max_length=5)),
                ('model_name', models.CharField(default='openai/gpt-4.1-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Base system prompt for this agent type')),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name': 'Agent Config',
                'verbose_name_plural': 'Agent Configs',
                'unique_together': {('workspace', 'agent_type')},
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['workspace', 'status'], name='agentsess_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['session', 'created_at'], name='agentmsg_sess_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['session', 'created_at'], name='actionlog_sess_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolpermission',
            unique_together={('workspace', 'user', 'tool_name')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplate',
            unique_together={('workspace', 'key')},
        ),
    ]
