# Generated by Django 5.2.13 on 2026-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='source',
            field=models.CharField(choices=[('agent_tab', 'Agent Tab'), ('chat_command', 'Chat Command'), ('batch_api', 'Batch API')], default='agent_tab', help_text='Where the session was triggered from (analytics + UI hints)', max_length=20),
        ),
    ]
