# Generated by Django 5.2.13 on 2026-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_agentsession_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='processed',
            field=models.BooleanField(db_index=True, default=True, help_text='EC-12: user commands sent during active tool execution are persisted as processed=False and dequeued by the orchestrator after the current tool completes.'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['session', 'role', 'processed'], name='agentmsg_sess_role_proc_idx'),
        ),
    ]
