# Generated by Django 5.2.13 on 2026-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0003_agentmessage_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='AC-31/AC-33: shared identifier across sibling sessions created by a single batch request. NULL for non-batch sessions.', null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='batch_position',
            field=models.IntegerField(default=0, help_text='AC-33: 0-indexed position within a batch (sequential ordering).'),
        ),
    ]
