# Generated by Django 5.2.13 on 2026-04-30 04:23

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0004_agentsession_batch_id'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkspaceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reflection_cadence_sessions', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('skill_creation_min_tool_calls', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('memory_char_limit', models.IntegerField(default=2200, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(4000)])),
                ('profile_char_limit', models.IntegerField(default=1375, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workspace_config', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name': 'Agent Workspace Config',
                'verbose_name_plural': 'Agent Workspace Configs',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('content_md', models.TextField(help_text='Markdown body of the skill (the "how-to").')),
                ('version', models.IntegerField(default=1)),
                ('trigger_type', models.CharField(choices=[('auto_complex_task', 'Auto: Complex Task'), ('auto_error_recovery', 'Auto: Error Recovery'), ('user_correction', 'User Correction'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30)),
                ('applicable_agent_types', models.JSONField(blank=True, default=list, help_text='List of agent_type values this skill applies to.')),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
                ('created_by_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to='agent_app.agentsession')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name': 'Agent Skill',
                'verbose_name_plural': 'Agent Skills',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('content_md', models.TextField()),
                ('patch_summary', models.TextField(blank=True, default='', help_text='1-2 sentence rationale for this version (why was it created/patched).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agent_app.skill')),
            ],
            options={
                'verbose_name': 'Skill Version',
                'verbose_name_plural': 'Skill Versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_md', models.TextField(blank=True, default='', help_text='Compact Markdown profile that the agent has inferred about this user.', max_length=1375, validators=[django.core.validators.MaxLengthValidator(1375)])),
                ('dialect_reasoning', models.TextField(blank=True, default='', help_text='Unbounded scratchpad — last dialectic 3-pass reasoning (read-only for UI).')),
                ('last_dialectic_at', models.DateTimeField(blank=True, null=True)),
                ('dialect_cadence_sessions', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user_profiles', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name': 'Agent User Profile',
                'verbose_name_plural': 'Agent User Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_md', models.TextField(blank=True, default='', help_text='Compact Markdown summary of what the agent has learned about the workspace.', max_length=2200, validators=[django.core.validators.MaxLengthValidator(2200)])),
                ('last_consolidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_consolidated_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_memories', to='agent_app.agentsession')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory', to='workspace_app.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Memory',
                'verbose_name_plural': 'Workspace Memories',
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['workspace', 'deleted_at'], name='skill_ws_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=django.contrib.postgres.indexes.GinIndex(fields=['applicable_agent_types'], name='skill_agent_types_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='skillversion',
            unique_together={('skill', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('workspace', 'user')},
        ),
    ]
