# Generated by Django 5.2.13 on 2026-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0005_self_improvement_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='content_md',
            field=models.TextField(blank=True, default='', help_text='Compact Markdown profile that the agent has inferred about this user. Char-limit is enforced at the view layer using AgentWorkspaceConfig.profile_char_limit (admin-tunable).'),
        ),
        migrations.AlterField(
            model_name='workspacememory',
            name='content_md',
            field=models.TextField(blank=True, default='', help_text='Compact Markdown summary of what the agent has learned about the workspace. Char-limit is enforced at the view layer using AgentWorkspaceConfig.memory_char_limit (admin-tunable).'),
        ),
    ]
