# Generated by Django 5.2.13 on 2026-05-10 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('amazon_research', 'Amazon Research'), ('keyword_drilling', 'Keyword Drilling')], db_index=True, max_length=30)),
                ('keyword', models.CharField(max_length=200)),
                ('marketplace', models.CharField(blank=True, default='', max_length=20)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'context', '-created_at'], name='ush_user_ctx_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'context', 'keyword', 'marketplace'), name='uniq_user_search_history_entry')],
            },
        ),
    ]
