# Generated by Django 5.2.14 on 2026-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_add_user_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium'), ('business', 'Business')], db_index=True, default='free', max_length=16),
        ),
    ]
