# Generated by Django 5.2.13 on 2026-04-15 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_app', '0003_keywordproductcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_index=True, max_length=200, unique=True)),
                ('results', models.JSONField(default=list, help_text='List of related words from Datamuse API')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Synonym Cache',
                'verbose_name_plural': 'Synonym Caches',
            },
        ),
    ]
