# Generated by Django 5.2.13 on 2026-04-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_app', '0004_add_synonym_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nichekeyword',
            name='source',
            field=models.CharField(choices=[('research', 'Research'), ('amazon_search', 'Amazon Search'), ('web_search', 'Web Search'), ('manual', 'Manual'), ('manual_snippet', 'Manual Snippet'), ('junglescout', 'JungleScout')], db_index=True, default='manual', max_length=20),
        ),
    ]
