"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'Merch Miner')

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1:5173,http://localhost:5173').split(',')
CORS_ALLOWED_ORIGINS_ENV = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS_ENV.split(',')
else:
    # Development Fallback
    CORS_ALLOWED_ORIGINS = [
        'http://127.0.0.1:5173',
        'http://localhost:5173',
    ]
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SAMESITE = None if not DEBUG else 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = None if not DEBUG else 'Lax'
SESSION_COOKIE_SECURE = not DEBUG

# Custom user model here
AUTH_USER_MODEL = 'user_auth_app.User'
SITE_ID = 1

# Frontend URLs aus Environment (mit Fallback)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
FRONTEND_ACTIVATION_URL = os.environ.get('FRONTEND_ACTIVATION_URL', 'http://localhost:5173/activate')
FRONTEND_CONFIRM_PASSWORD_URL = os.environ.get('FRONTEND_CONFIRM_PASSWORD_URL', 'http://localhost:5173/password-reset/confirm')

# Google OAuth2 credentials
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# ----------------------------------------
# Email Backend & SMTP (Django)
# ----------------------------------------
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ----------------------------------------
# Simple JWT Settings
# ----------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('JWT',),
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': not DEBUG,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'None' if not DEBUG else 'Lax',
    'AUTH_COOKIE_DOMAIN': None,
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django.contrib.sites',
    'django_rq',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'user_auth_app',
    'workspace_app',
    'niche_app',
    'scraper_app',
    'niche_research_app',
    'research_app',
    'vector_app',
    'idea_app',
    'design_app',
    'keyword_app',
    'publish_app',
    'dashboard_app',
    'kanban_app',
    'search_app',
    'agent_app',
    'chat_attachments_app',
]

# django-allauth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    }
}

# allauth: skip email verification for social accounts (they are pre-verified by Google)
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True  # skip intermediate confirmation form → redirect directly to Google
SOCIALACCOUNT_AUTO_SIGNUP = True
# Use email as the unique identifier (matches our custom User model)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "postgres"),
        "USER": os.environ.get("DB_USER", "merch_miner_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "host.docker.internal"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "OPTIONS": {
            "options": f"-c search_path={os.environ.get('DB_SCHEMA', 'merch_miner')},public"
        }
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_LOCATION", default="redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "app"
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 900,
        'REDIS_CLIENT_KWARGS': {},
    },
    'scraper': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 1800,
        'REDIS_CLIENT_KWARGS': {},
    },
    'research': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 1200,
        'REDIS_CLIENT_KWARGS': {},
    },
    'slogan': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 1800,
        'REDIS_CLIENT_KWARGS': {},
    },
    'design': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 1800,
        'REDIS_CLIENT_KWARGS': {},
    },
    'agent': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 3600,
        'REDIS_CLIENT_KWARGS': {},
    },
    'search': {
        'HOST': os.environ.get("REDIS_HOST", default="redis"),
        'PORT': os.environ.get("REDIS_PORT", default=6379),
        'DB': os.environ.get("REDIS_DB", default=0),
        'DEFAULT_TIMEOUT': 300,
        'REDIS_CLIENT_KWARGS': {},
    },
}

# Scraper settings
SCRAPEOPS_API_KEY = os.environ.get('SCRAPEOPS_API_KEY', '')
SCRAPY_CONCURRENT_REQUESTS = int(os.environ.get('SCRAPY_CONCURRENT_REQUESTS', 1))

# ----------------------------------------
# Selector Health Check (PROJ-23)
# ----------------------------------------
# Maximum HTML snapshots to keep on disk per (asin, marketplace).
SELECTOR_HEALTH_CHECK_RETENTION = int(
    os.environ.get('SELECTOR_HEALTH_CHECK_RETENTION', '12'),
)
# Cron expression for the weekly health-check runner. Default: Mon 04:00 UTC.
SELECTOR_HEALTH_CHECK_SCHEDULE_CRON = os.environ.get(
    'SELECTOR_HEALTH_CHECK_SCHEDULE_CRON', '0 4 * * 1',
)

# ----------------------------------------
# OpenRouter (LLM API via OpenAI-compatible endpoint)
# ----------------------------------------
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_BASE_URL = os.environ.get(
    'OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1',
)
OPENROUTER_AGENT_API_KEY = os.environ.get('OPENROUTER_AGENT_API_KEY', '')
AGENT_BUDGET_WARNING_THRESHOLD = os.environ.get('AGENT_BUDGET_WARNING_THRESHOLD', '')
# EC-15: Per-sub-agent timeout for orchestrator delegate calls (seconds, default 10 min)
AGENT_SUBAGENT_TIMEOUT_SEC = int(os.environ.get('AGENT_SUBAGENT_TIMEOUT_SEC', '600'))

# ----------------------------------------
# SearXNG (web search for niche research)
# ----------------------------------------
SEARXNG_BASE_URL = os.environ.get('SEARXNG_BASE_URL', '')

# ----------------------------------------
# Deep Web Search — Vane + Crawl4ai (PROJ-17)
# ----------------------------------------
VANE_API_URL = os.environ.get('VANE_API_URL', '')
CRAWL4AI_API_URL = os.environ.get('CRAWL4AI_API_URL', '')
VANE_DEFAULT_MODEL = os.environ.get('VANE_DEFAULT_MODEL', 'gpt-4.1-mini')
VANE_EMBEDDING_MODEL = os.environ.get('VANE_EMBEDDING_MODEL', 'text-embedding-3-small')

# Feature flag — gates Vector DB embedding signal (PROJ-15 dependency).
# Default true locally, set false in prod until PROJ-15 backfill is complete.
VECTOR_DB_ENABLED = os.environ.get('VECTOR_DB_ENABLED', 'true').lower() in ('true', '1', 'yes')

# ----------------------------------------
# Langfuse Observability
# ----------------------------------------
# ----------------------------------------
# Vector Database / Embeddings (PROJ-15)
# ----------------------------------------
EMBEDDING_MODEL = os.environ.get('EMBEDDING_MODEL', 'text-embedding-3-small')
EMBEDDING_DIMENSIONS = int(os.environ.get('EMBEDDING_DIMENSIONS', '1536'))

# ----------------------------------------
# JungleScout (Keyword Research — PROJ-10)
# ----------------------------------------
JUNGLESCOUT_API_KEY_NAME = os.environ.get('JUNGLESCOUT_API_KEY_NAME', '')
JUNGLESCOUT_API_KEY = os.environ.get('JUNGLESCOUT_API_KEY', '')
JUNGLESCOUT_DEFAULT_MARKETPLACE = os.environ.get('JUNGLESCOUT_DEFAULT_MARKETPLACE', 'us')

# ----------------------------------------
# Publish / Cloud Import (PROJ-11)
# ----------------------------------------
GOOGLE_DRIVE_CLIENT_ID = os.environ.get('GOOGLE_DRIVE_CLIENT_ID', '')
GOOGLE_DRIVE_CLIENT_SECRET = os.environ.get('GOOGLE_DRIVE_CLIENT_SECRET', '')
ONEDRIVE_CLIENT_ID = os.environ.get('ONEDRIVE_CLIENT_ID', '')
ONEDRIVE_CLIENT_SECRET = os.environ.get('ONEDRIVE_CLIENT_SECRET', '')

# ----------------------------------------
# Django Channels (WebSocket — Desktop Upload App)
# ----------------------------------------
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(
                os.environ.get('REDIS_HOST', 'redis'),
                int(os.environ.get('REDIS_PORT', 6379)),
            )],
        },
    },
}

# Upload file limits
MAX_DESIGN_UPLOAD_SIZE = 25 * 1024 * 1024  # 25 MB

LANGFUSE_PUBLIC_KEY = os.environ.get('LANGFUSE_PUBLIC_KEY', '')
LANGFUSE_SECRET_KEY = os.environ.get('LANGFUSE_SECRET_KEY', '')
LANGFUSE_HOST = os.environ.get('LANGFUSE_HOST', 'https://langfuse.mariowinter.com')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user_auth_app.api.authentication.CookieJWTAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '500/hour' if DEBUG else '20/hour',
        'user': '10000/day' if DEBUG else '1000/day',
        'avatar': '50/hour',
        'invite': '20/hour',
        'semantic_search': '30/minute',
        'semantic_search_daily': '500/day',
        'product_count_scrape': '10/hour',
        'ai_improve': '10/min',
    },
}

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'origin-when-cross-origin'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
