# Generated by Django 5.2.13 on 2026-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('niche_created', 'Niche Created'), ('niche_archived', 'Niche Archived'), ('niche_status_changed', 'Niche Status Changed'), ('research_completed', 'Research Completed'), ('research_failed', 'Research Failed'), ('idea_created', 'Idea Created'), ('idea_approved', 'Idea Approved'), ('idea_rejected', 'Idea Rejected'), ('design_generated', 'Design Generated'), ('design_approved', 'Design Approved'), ('listing_ready', 'Listing Ready'), ('listing_published', 'Listing Published'), ('upload_completed', 'Upload Completed'), ('upload_failed', 'Upload Failed'), ('agent_session_started', 'Agent Session Started'), ('agent_session_completed', 'Agent Session Completed'), ('agent_session_failed', 'Agent Session Failed'), ('agent_awaiting_approval', 'Agent Awaiting Approval')], db_index=True, max_length=50),
        ),
    ]
