# Generated by Django 5.2.12 on 2026-03-27 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niche_app', '0004_add_research_retry_count'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SloganNodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(choices=[('analyze_original', 'Analyze Original'), ('discover_niches', 'Discover Niches'), ('validate_products', 'Validate Products'), ('adapt_slogans', 'Adapt Slogans'), ('quality_check', 'Quality Check')], max_length=50, unique=True)),
                ('model_name', models.CharField(default='openai/gpt-4.1-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slogan Node Config',
                'verbose_name_plural': 'Slogan Node Configs',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_product_url', models.URLField(blank=True, default='')),
                ('slogan_text', models.TextField()),
                ('is_manual', models.BooleanField(default=True)),
                ('signal_type', models.CharField(blank=True, choices=[('self', 'Self'), ('other', 'Other')], max_length=10, null=True)),
                ('creative_modules_used', models.JSONField(blank=True, default=list)),
                ('emotional_archetype', models.CharField(blank=True, default='', max_length=100)),
                ('buyer_voice_pattern', models.TextField(blank=True, default='')),
                ('stylistic_device', models.CharField(blank=True, default='', max_length=100)),
                ('pattern_used', models.CharField(blank=True, default='', max_length=200)),
                ('why_it_works', models.TextField(blank=True, default='')),
                ('market_confidence', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('for_review', 'For Review')], db_index=True, default='pending', max_length=20)),
                ('was_changed', models.BooleanField(default=False)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ideas', to=settings.AUTH_USER_MODEL)),
                ('niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='niche_app.niche')),
                ('source_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_ideas', to='idea_app.idea')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaAdaptationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_niche_ids', models.JSONField(default=list, help_text='List of target niche UUIDs')),
                ('niche_results', models.JSONField(blank=True, default=dict, help_text='Per-niche approval/rejection results')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of all SloganNodeConfig at run start (audit trail)')),
                ('completed_nodes', models.JSONField(blank=True, default=list, help_text='Node names that completed successfully')),
                ('current_node', models.CharField(blank=True, default='', help_text='Currently running node name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('rq_job_id', models.CharField(blank=True, default='', help_text='RQ job ID for cancellation support', max_length=100)),
                ('source_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_runs', to='idea_app.idea')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_adaptation_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_runs', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='adaptation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ideas', to='idea_app.ideaadaptationrun'),
        ),
        migrations.AddIndex(
            model_name='ideaadaptationrun',
            index=models.Index(fields=['workspace', 'status'], name='adapt_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['workspace', 'niche'], name='idea_workspace_niche_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['workspace', 'status'], name='idea_workspace_status_idx'),
        ),
    ]
