# Generated by Django 5.2.12 on 2026-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
