# Generated by Django 5.2.12 on 2026-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0003_ideafiltertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('for_review', 'For Review'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20),
        ),
    ]
