import type { Idea } from '../types';

/**
 * DEV-ONLY: Mock ideas for styling preview when the API returns no data.
 * Remove before production deployment.
 */

const now = new Date().toISOString();
const BASE = {
  workspace: 'mock-ws',
  source_product_url: '',
  is_manual: false,
  was_changed: false,
  change_reason: '',
  creative_modules_used: [],
  adaptation_run: null,
  created_by: 1,
  created_at: now,
} as const;

const SRC_ID = 'mock-src-001';
const SRC_SUMMARY = { id: SRC_ID, slogan_text: 'Life Is Better With A Dog By Your Side' };

export const MOCK_IDEAS: Idea[] = [
  // ── Source idea ──
  {
    ...BASE,
    id: SRC_ID,
    slogan_text: 'Life Is Better With A Dog By Your Side',
    niche: 'niche-dog',
    niche_name: 'Dog Lovers',
    source_idea: null,
    source_idea_summary: null,
    signal_type: null,
    market_confidence: null,
    emotional_archetype: 'Companionship',
    buyer_voice_pattern: 'Warm & Affirming',
    stylistic_device: 'Parallel Structure',
    pattern_used: 'Emotional Bond',
    why_it_works: 'Taps into the universal dog-owner bond — simple, warm, shareable.',
    status: 'approved',
  },

  // ── 5x SELF adaptations ──
  {
    ...BASE,
    id: 'mock-self-001',
    slogan_text: 'Life Is Better When You Teach Little Minds',
    niche: 'niche-teacher',
    niche_name: 'Teacher Life',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'self',
    market_confidence: 'High',
    emotional_archetype: 'Purpose',
    buyer_voice_pattern: 'Warm & Affirming',
    stylistic_device: 'Parallel Structure',
    pattern_used: 'Emotional Bond',
    why_it_works: 'Keeps the warmth of the original, repurposed for teacher identity.',
    status: 'approved',
  },
  {
    ...BASE,
    id: 'mock-self-002',
    slogan_text: 'Life Is Better With Paws And Coffee',
    niche: 'niche-catmom',
    niche_name: 'Cat Mom Life',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'self',
    market_confidence: 'Medium',
    emotional_archetype: 'Comfort',
    buyer_voice_pattern: 'Cozy & Relatable',
    stylistic_device: 'Compound Imagery',
    pattern_used: 'Lifestyle Fusion',
    why_it_works: 'Blends pet love with daily ritual — dual-identity appeal.',
    status: 'pending',
  },
  {
    ...BASE,
    id: 'mock-self-003',
    slogan_text: 'Life Is Better With Flour On Your Hands',
    niche: 'niche-baking',
    niche_name: 'Baking Lovers',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'self',
    market_confidence: 'High',
    emotional_archetype: 'Joy',
    buyer_voice_pattern: 'Warm & Nostalgic',
    stylistic_device: 'Sensory Detail',
    pattern_used: 'Hands-On Passion',
    why_it_works: 'Sensory imagery makes it tangible — flour = craft love.',
    status: 'approved',
  },
  {
    ...BASE,
    id: 'mock-self-004',
    slogan_text: 'Life Is Better With A Rod And A Sunrise',
    niche: 'niche-fishing',
    niche_name: 'Fishing & Outdoors',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'self',
    market_confidence: 'Medium',
    emotional_archetype: 'Escape',
    buyer_voice_pattern: 'Calm & Reflective',
    stylistic_device: 'Scene Painting',
    pattern_used: 'Nature Bond',
    why_it_works: 'Evokes peaceful morning fishing — escape appeal.',
    status: 'for_review',
    was_changed: true,
    change_reason: 'Quality check: "rod and a sunrise" tested better than "fishing pole".',
  },
  {
    ...BASE,
    id: 'mock-self-005',
    slogan_text: 'Life Is Better With Yarn And A Good Podcast',
    niche: 'niche-knitting',
    niche_name: 'Knitting & Crochet',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'self',
    market_confidence: 'Low',
    emotional_archetype: 'Serenity',
    buyer_voice_pattern: 'Gentle & Witty',
    stylistic_device: 'Dual Activity',
    pattern_used: 'Cozy Ritual',
    why_it_works: 'Niche-specific pairing — yarn + podcast = identity signal.',
    status: 'pending',
  },

  // ── 5x OTHER adaptations ──
  {
    ...BASE,
    id: 'mock-other-001',
    slogan_text: 'Every Rep Brings You Closer To The Best Version',
    niche: 'niche-gym',
    niche_name: 'Gym Motivation',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'other',
    market_confidence: 'High',
    emotional_archetype: 'Growth',
    buyer_voice_pattern: 'Motivational & Direct',
    stylistic_device: 'Progressive Imagery',
    pattern_used: 'Self-Improvement',
    why_it_works: 'Converts the "better" frame into gym grind — aspirational hook.',
    status: 'approved',
  },
  {
    ...BASE,
    id: 'mock-other-002',
    slogan_text: 'Code All Night, Debug All Morning',
    niche: 'niche-dev',
    niche_name: 'Developer Humor',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'other',
    market_confidence: 'High',
    emotional_archetype: 'Resilience',
    buyer_voice_pattern: 'Self-Deprecating',
    stylistic_device: 'Antithesis',
    pattern_used: 'Work-Life Irony',
    why_it_works: 'Universal dev experience — relatable grind humor.',
    status: 'approved',
  },
  {
    ...BASE,
    id: 'mock-other-003',
    slogan_text: 'Life Is Better At The Grill With Dad',
    niche: 'niche-dad',
    niche_name: 'Dad Jokes & BBQ',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'other',
    market_confidence: 'Low',
    emotional_archetype: 'Nostalgia',
    buyer_voice_pattern: 'Humorous & Casual',
    stylistic_device: 'Scene Painting',
    pattern_used: 'Family Moment',
    why_it_works: 'Low overlap — BBQ niche prefers punchlines over warmth.',
    status: 'rejected',
  },
  {
    ...BASE,
    id: 'mock-other-004',
    slogan_text: 'Powered By Plants And Positive Vibes',
    niche: 'niche-vegan',
    niche_name: 'Vegan Lifestyle',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'other',
    market_confidence: 'Medium',
    emotional_archetype: 'Identity',
    buyer_voice_pattern: 'Upbeat & Proud',
    stylistic_device: 'Alliteration',
    pattern_used: 'Lifestyle Statement',
    why_it_works: 'Alliterative energy + identity badge — tribe signaling.',
    status: 'pending',
  },
  {
    ...BASE,
    id: 'mock-other-005',
    slogan_text: 'Scrubs, Coffee, Repeat — That\'s The Shift',
    niche: 'niche-nurse',
    niche_name: 'Nurse Humor',
    source_idea: SRC_ID,
    source_idea_summary: SRC_SUMMARY,
    signal_type: 'other',
    market_confidence: 'Medium',
    emotional_archetype: 'Solidarity',
    buyer_voice_pattern: 'Insider Humor',
    stylistic_device: 'List + Punchline',
    pattern_used: 'Daily Grind',
    why_it_works: 'Insider shorthand — "scrubs" = instant tribe recognition.',
    status: 'for_review',
  },

  // ── Standalone cards (no group) ──
  {
    ...BASE,
    id: 'mock-standalone-001',
    slogan_text: 'Fueled By Caffeine And Chaos',
    niche: 'niche-nurse',
    niche_name: 'Nurse Humor',
    source_idea: null,
    source_idea_summary: null,
    signal_type: null,
    market_confidence: null,
    emotional_archetype: 'Resilience',
    buyer_voice_pattern: 'Self-Deprecating Humor',
    stylistic_device: 'Parallel Nouns',
    pattern_used: 'Dual Identity',
    why_it_works: 'Classic nurse humor formula — chaos + caffeine = instant relatability.',
    status: 'pending',
  },
  {
    ...BASE,
    id: 'mock-standalone-002',
    slogan_text: 'Born To Fish, Forced To Work',
    niche: 'niche-fishing',
    niche_name: 'Fishing & Outdoors',
    source_idea: null,
    source_idea_summary: null,
    signal_type: null,
    market_confidence: null,
    emotional_archetype: 'Escape',
    buyer_voice_pattern: 'Dry Humor',
    stylistic_device: 'Antithesis',
    pattern_used: 'Passion vs. Reality',
    why_it_works: 'Evergreen POD formula — "born to X, forced to Y" always sells.',
    status: 'for_review',
    was_changed: true,
    change_reason: 'Quality check: adjusted from "Made To Fish" — "Born To" has 3x higher BSR.',
  },

  // ── Niche-less orphans ──
  {
    ...BASE,
    id: 'mock-orphan-001',
    slogan_text: 'Sorry, I Was Thinking About Tacos',
    niche: null,
    niche_name: null,
    source_idea: null,
    source_idea_summary: null,
    signal_type: null,
    market_confidence: null,
    emotional_archetype: 'Humor',
    buyer_voice_pattern: 'Relatable & Playful',
    stylistic_device: 'Inner Monologue',
    pattern_used: '',
    why_it_works: '',
    status: 'pending',
    is_manual: true,
  },
  {
    ...BASE,
    id: 'mock-orphan-002',
    slogan_text: 'Weekend Forecast: 100% Chance Of Wine',
    niche: null,
    niche_name: null,
    source_idea: null,
    source_idea_summary: null,
    signal_type: null,
    market_confidence: null,
    emotional_archetype: 'Indulgence',
    buyer_voice_pattern: 'Cheeky & Fun',
    stylistic_device: 'Weather Metaphor',
    pattern_used: '',
    why_it_works: '',
    status: 'approved',
    is_manual: true,
  },
];
