# Generated by Django 5.2.12 on 2026-03-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_research_app', '0002_seed_research_node_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicheresearch',
            name='completed_nodes',
            field=models.JSONField(blank=True, default=list, help_text='Node names that completed successfully'),
        ),
        migrations.AddField(
            model_name='nicheresearch',
            name='current_node',
            field=models.CharField(blank=True, default='', help_text='Currently running node name', max_length=50),
        ),
        migrations.AddField(
            model_name='nicheresearch',
            name='marketplace',
            field=models.CharField(db_index=True, default='amazon_com', help_text='Marketplace used for scraping', max_length=20),
        ),
        migrations.AddField(
            model_name='nicheresearch',
            name='product_type',
            field=models.CharField(default='t_shirt', help_text='MBA product type filter', max_length=20),
        ),
        migrations.AddField(
            model_name='nicheresearch',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retries on this record'),
        ),
    ]
