# Generated by Django 5.2.12 on 2026-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_research_app', '0004_add_cancel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicheresearch',
            name='brand_filtered_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of products filtered out by brand blacklist'),
        ),
        migrations.AddField(
            model_name='nicheresearchproduct',
            name='brand_blocked',
            field=models.BooleanField(default=False, help_text='Whether this product was blocked by brand blacklist'),
        ),
    ]
