# Generated by Django 5.2.13 on 2026-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_research_app', '0005_brand_filter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicheresearch',
            name='product_limit',
            field=models.PositiveSmallIntegerField(default=50, help_text='How many products this run analyzed (allowed range 10-200). Audit value: also reused on force-refresh to repeat the same depth of analysis.'),
        ),
    ]
