# Generated by Django 5.2.14 on 2026-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_research_app', '0006_add_product_limit_to_niche_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicheproductvisionanalysis',
            name='accessory_descriptors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nicheproductvisionanalysis',
            name='font_combination_descriptors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nicheproductvisionanalysis',
            name='typography_descriptors',
            field=models.TextField(blank=True, default=''),
        ),
    ]
