# Generated by Django 5.2.12 on 2026-03-27 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niche_app', '0005_niche_current_round'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text='Auto-generated from first query if not set.', max_length=200)),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('niche_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='niche_app.niche')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('search_query', 'Search Query'), ('search_result', 'Search Result'), ('crawl_request', 'Crawl Request'), ('crawl_result', 'Crawl Result'), ('agent_message', 'Agent Message')], default='search_query', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list, help_text='Array of {title, url, snippet} from Vane results.')),
                ('search_mode', models.CharField(blank=True, help_text='speed, balanced, or quality.', max_length=10, null=True)),
                ('search_sources', models.JSONField(blank=True, help_text='Array of source types: web, academic, discussions.', null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='search_app.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('is_system', models.BooleanField(default=False, help_text='System tags are auto-created and cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_tags', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_tags', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='search_app.chattag'),
        ),
        migrations.CreateModel(
            name='SearchUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('search', 'Search'), ('deep_crawl', 'Deep Crawl')], max_length=10)),
                ('query', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=2000)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_usage_logs', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Full crawled Markdown content or snippet text.')),
                ('content_type', models.CharField(choices=[('snippet', 'Snippet'), ('full_crawl', 'Full Crawl')], default='snippet', max_length=10)),
                ('crawl_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Page metadata, word count, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to='search_app.chatmessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_search_results', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatmsg_sess_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chattag',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['workspace', '-updated_at'], name='chatsess_ws_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_by', '-updated_at'], name='chatsess_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='searchusagelog',
            index=models.Index(fields=['workspace', 'action'], name='searchusage_ws_action_idx'),
        ),
        migrations.AddIndex(
            model_name='searchusagelog',
            index=models.Index(fields=['workspace', '-created_at'], name='searchusage_ws_created_idx'),
        ),
    ]
