# Generated by Django 5.2.13 on 2026-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='tags',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('search_query', 'Search Query'), ('search_result', 'Search Result'), ('crawl_request', 'Crawl Request'), ('crawl_result', 'Crawl Result')], default='search_query', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatTag',
        ),
    ]
