# Generated by Django 5.2.13 on 2026-04-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
        ('search_app', '0002_remove_chatsession_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='agent_session',
            field=models.ForeignKey(blank=True, help_text='Set for workflow_trigger / workflow_card messages — links to PROJ-18 AgentSession.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_chat_messages', to='agent_app.agentsession'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('search_query', 'Search Query'), ('search_result', 'Search Result'), ('crawl_request', 'Crawl Request'), ('crawl_result', 'Crawl Result'), ('workflow_trigger', 'Workflow Trigger'), ('workflow_card', 'Workflow Card')], default='search_query', max_length=20),
        ),
    ]
