# Generated by Django 5.2.13 on 2026-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_chatmessage_agent_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Random token used to access the shared chat via public URL.', max_length=64, null=True, unique=True),
        ),
    ]
