# Generated by Django 5.2.14 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_chatsession_conversation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='generate_slogans_payload',
            field=models.JSONField(blank=True, help_text='Structured slogan rows from the niche-RAG agent.', null=True),
        ),
    ]
