# Generated by Django 5.2.14 on 2026-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0006_chatmessage_generate_slogans_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chunks_used',
            field=models.JSONField(blank=True, help_text='Retrieved RAG chunks shown in the ThinkingStrip ExpandedPanel.', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thinking_stages',
            field=models.JSONField(blank=True, help_text='Ordered ThinkingStrip stage rows (active / done / warning / error).', null=True),
        ),
    ]
