# Generated by Django 5.2.14 on 2026-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0007_chatmessage_chunks_used_and_thinking_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('search_query', 'Search Query'), ('search_result', 'Search Result'), ('crawl_request', 'Crawl Request'), ('crawl_result', 'Crawl Result'), ('workflow_trigger', 'Workflow Trigger'), ('workflow_card', 'Workflow Card'), ('error', 'Error')], default='search_query', max_length=20),
        ),
    ]
