# Generated by Django 5.2.14 on 2026-05-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0010_niche_bom_cache'),
        ('search_app', '0008_chatmessage_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='referenced_niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_in_messages', to='niche_app.niche'),
        ),
    ]
