# Generated by Django 5.2.14 on 2026-05-29 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0010_niche_bom_cache'),
        ('search_app', '0009_chatmessage_referenced_niche'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='group_ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['ordering', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='search_app.chatgroup'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['group', 'group_ordering'], name='chatsess_group_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroup',
            index=models.Index(fields=['workspace', 'ordering'], name='chatgroup_ws_ordering_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatgroup',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='chatgroup_workspace_name_unique'),
        ),
    ]
