# Generated by Django 5.2.12 on 2026-03-27 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idea_app', '0001_initial'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingSettings',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='processing_settings', serialize=False, to='workspace_app.workspace')),
                ('bg_removal_provider', models.CharField(choices=[('rembg', 'rembg (self-hosted)'), ('api', 'External API')], default='rembg', max_length=20)),
                ('bg_removal_api_key', models.CharField(blank=True, default='', help_text='Encrypted API key for external BG removal service', max_length=500)),
                ('upscale_provider', models.CharField(choices=[('pica', 'Pica.js (client-side)'), ('api', 'External API'), ('auto', 'Auto (threshold-based)')], default='auto', max_length=20)),
                ('upscale_api_key', models.CharField(blank=True, default='', help_text='Encrypted API key for external upscaling service', max_length=500)),
                ('upscale_auto_threshold', models.IntegerField(default=3000, help_text='Images >= this px use Pica.js; below use API')),
            ],
            options={
                'verbose_name': 'Processing Settings',
                'verbose_name_plural': 'Processing Settings',
            },
        ),
        migrations.CreateModel(
            name='DesignGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(choices=[('gemini_flash', 'Gemini Flash'), ('gemini_pro', 'Gemini Pro'), ('gpt_image', 'GPT Image'), ('flux', 'Flux')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('prompt_used', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('rq_job_id', models.CharField(blank=True, default='', help_text='RQ job ID for status tracking', max_length=100)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='idea_app.idea')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_design_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.FileField(blank=True, default='', upload_to='designs/generated/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('is_manual', models.BooleanField(default=False)),
                ('background_color', models.CharField(choices=[('light_gray', 'Light Gray'), ('neon_pink', 'Neon Pink'), ('neon_green', 'Neon Green')], default='light_gray', max_length=20)),
                ('source_image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('prompt_analysis', models.JSONField(blank=True, default=dict, help_text='7-step Gemini 3 Architect analysis output')),
                ('upscaled_file', models.FileField(blank=True, default='', upload_to='designs/upscaled/%Y/%m/')),
                ('bg_removed_file', models.FileField(blank=True, default='', upload_to='designs/bg_removed/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='idea_app.idea')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='workspace_app.workspace')),
                ('generation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='design_app.designgenerationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tools', models.JSONField(default=list, help_text='Ordered list of {tool_name, params, condition} objects')),
                ('is_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_pipelines', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('upscale', 'Upscale'), ('bg_remove', 'Background Remove')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('result_file', models.FileField(blank=True, default='', upload_to='designs/processed/%Y/%m/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rq_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='design_app.design')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='designgenerationrun',
            index=models.Index(fields=['idea', 'status'], name='designrun_idea_status_idx'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['workspace', 'idea'], name='design_ws_idea_idx'),
        ),
        migrations.AddIndex(
            model_name='designprocessingjob',
            index=models.Index(fields=['design', 'type'], name='procjob_design_type_idx'),
        ),
    ]
