# Generated by Django 5.2.12 on 2026-03-30 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0001_initial'),
        ('idea_app', '0005_idea_board_layout'),
        ('niche_app', '0006_add_collected_product'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='idea_app.idea'),
        ),
        migrations.AlterField(
            model_name='designgenerationrun',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_runs', to='idea_app.idea'),
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('board_layout', models.JSONField(blank=True, default=None, help_text='React Flow node positions + edges', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_design_projects', to=settings.AUTH_USER_MODEL)),
                ('niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_projects', to='niche_app.niche')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_projects', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignProjectDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_projects_through', to='design_app.design')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_designs', to='design_app.designproject')),
            ],
        ),
        migrations.AddField(
            model_name='designproject',
            name='designs',
            field=models.ManyToManyField(blank=True, related_name='projects', through='design_app.DesignProjectDesign', to='design_app.design'),
        ),
        migrations.AddIndex(
            model_name='designprojectdesign',
            index=models.Index(fields=['project', 'design'], name='projdesign_proj_design_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designprojectdesign',
            unique_together={('project', 'design')},
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['workspace'], name='designproject_ws_idx'),
        ),
    ]
