# Generated by Django 5.2.12 on 2026-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0002_alter_design_idea_alter_designgenerationrun_idea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='processed_file',
            field=models.FileField(blank=True, default='', upload_to='designs/processed/%Y/%m/'),
        ),
    ]
