# Generated by Django 5.2.12 on 2026-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0004_phase_g_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designprojectidea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
