# Generated by Django 5.2.13 on 2026-04-10 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0006_expand_model_choices'),
        ('scraper_app', '0014_amazonproduct_prompt_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('asin', models.CharField(blank=True, default='', max_length=20)),
                ('prompt_analysis', models.JSONField(blank=True, default=None, help_text='AI vision analysis of the reference image', null=True)),
                ('position', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='design_app.designproject')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_references', to='scraper_app.amazonproduct')),
            ],
            options={
                'ordering': ['position', '-added_at'],
                'indexes': [models.Index(fields=['project'], name='projref_project_idx')],
                'unique_together': {('project', 'image_url')},
            },
        ),
    ]
