# Generated by Django 5.2.13 on 2026-04-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0007_project_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='designgenerationrun',
            name='source_image_url',
            field=models.URLField(blank=True, default='', help_text='Reference image URL for multimodal generation', max_length=2048),
        ),
    ]
