# Generated by Django 5.2.13 on 2026-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0009_add_generation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designgenerationrun',
            name='generation_mode',
            field=models.CharField(choices=[('text_to_image', 'Text to Image'), ('image_to_image', 'Image to Image'), ('image_to_image_remix', 'Image to Image (Remix)'), ('image_to_image_edit', 'Image to Image (Edit)')], db_index=True, default='text_to_image', help_text='Generation mode: text_to_image or image_to_image', max_length=20),
        ),
    ]
