# Generated by Django 5.2.14 on 2026-05-17 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0012_proj27_upscaler'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designgenerationrun',
            name='background_color',
            field=models.CharField(choices=[('light_gray', 'Light Gray'), ('neon_pink', 'Neon Pink'), ('neon_green', 'Neon Green')], default='light_gray', help_text='Background color selected in UI (PROJ-34); used by image_generator to inject the exact hex into the user message.', max_length=20),
        ),
        migrations.AddField(
            model_name='designgenerationrun',
            name='prompt_polished',
            field=models.TextField(blank=True, help_text='Polished prompt actually sent to the model (PROJ-34, debug).', null=True),
        ),
        migrations.AddField(
            model_name='processingsettings',
            name='polish_builder_prompts_enabled',
            field=models.BooleanField(default=True, help_text='When True, prompts created by the Prompt Builder are polished by a small LLM before generation (PROJ-34).'),
        ),
        migrations.CreateModel(
            name='BuilderPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('config', models.JSONField(default=dict, help_text='Builder config: slogans, styles, warp, bg_color, niche_context_enabled.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_builder_presets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_presets', to='design_app.designproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_presets', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'is_deleted'], name='builderpreset_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'name'), name='builderpreset_unique_name_per_project_active')],
            },
        ),
    ]
