# Generated by Django 5.2.14 on 2026-05-18 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0013_designgenerationrun_background_color_and_more'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSpatial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('prompt_text', models.TextField()),
                ('source_kind', models.CharField(choices=[('upload', 'Image upload'), ('reference', 'Project reference'), ('design', 'Generated design')], max_length=16)),
                ('source_image_ref', models.CharField(blank=True, default='', max_length=64)),
                ('source_image_file', models.ImageField(blank=True, null=True, upload_to='custom_spatials/%Y/%m/')),
                ('is_unsafe', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_custom_spatials', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_spatials', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workspace', 'name'), name='uniq_custom_spatial_name_per_ws')],
            },
        ),
    ]
