# Generated by Django 5.2.14 on 2026-05-20 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0015_customtypography'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderpreset',
            name='config',
            field=models.JSONField(default=dict, help_text='Builder config: slogans, styles, bg_color, niche_context_enabled, slots.'),
        ),
        migrations.CreateModel(
            name='NicheCardPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset_hash', models.CharField(db_index=True, max_length=64)),
                ('preset_label', models.CharField(max_length=200)),
                ('slot_spatial_configuration', models.TextField(blank=True, default='')),
                ('slot_visual_description', models.TextField(blank=True, default='')),
                ('slot_typography_adjectives', models.TextField(blank=True, default='')),
                ('slot_font_combination', models.TextField(blank=True, default='')),
                ('slot_accessories', models.TextField(blank=True, default='')),
                ('slot_style_dna', models.TextField(blank=True, default='')),
                ('slot_extra_context', models.TextField(blank=True, default='')),
                ('spatial_is_raw', models.BooleanField(default=False)),
                ('visual_is_raw', models.BooleanField(default=False)),
                ('typography_is_raw', models.BooleanField(default=False)),
                ('font_combination_is_raw', models.BooleanField(default=False)),
                ('accessories_is_raw', models.BooleanField(default=False)),
                ('style_dna_is_raw', models.BooleanField(default=False)),
                ('extra_context_is_raw', models.BooleanField(default=False)),
                ('reference_thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('source_card_type', models.CharField(choices=[('top', 'Top'), ('mix_most_common', 'Mix · Most-Common'), ('mix_edgy', 'Mix · Edgy'), ('mix_safe', 'Mix · Safe')], max_length=20)),
                ('source_card_references', models.JSONField(blank=True, default=list)),
                ('is_in_history', models.BooleanField(db_index=True, default=True)),
                ('is_in_custom', models.BooleanField(db_index=True, default=False)),
                ('custom_promoted_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_niche_presets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niche_card_presets', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-last_clicked_at'],
                'indexes': [models.Index(fields=['workspace', 'is_in_history', '-last_clicked_at'], name='nichepreset_ws_hist_idx'), models.Index(fields=['workspace', 'is_in_custom', '-custom_promoted_at'], name='nichepreset_ws_custom_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'preset_hash'), name='uniq_preset_hash_per_ws')],
            },
        ),
    ]
