# Generated by Django 5.2.14 on 2026-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0016_nichecardpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nichecardpreset',
            name='source_card_type',
            field=models.CharField(choices=[('top', 'Top'), ('mix_most_common', 'Mix · Most-Common'), ('mix_edgy', 'Mix · Edgy'), ('mix_safe', 'Mix · Safe'), ('collection', 'Collection')], max_length=20),
        ),
    ]
