# Generated by Django 5.2.14 on 2026-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0017_add_collection_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designgenerationrun',
            name='model_name',
            field=models.CharField(choices=[('gemini_flash', 'Gemini Flash'), ('gemini_pro', 'Gemini Pro'), ('gpt_image', 'GPT Image'), ('flux', 'Flux'), ('google/gemini-3.1-flash-preview-image-generation', 'Nano Banana 2'), ('google/gemini-3-pro-preview-image-generation', 'Nano Banana Pro'), ('google/gemini-2.5-flash-preview-image-generation', 'Nano Banana'), ('openai/gpt-5-image', 'GPT-5 Image'), ('openai/gpt-5-image-mini', 'GPT-5 Mini'), ('openai/gpt-5.4-image-2', 'GPT-5.4 Image 2'), ('black-forest-labs/flux-1.1-pro', 'Flux 1.1 Pro'), ('bytedance-seed/seedream-4.5', 'Seedream 4.5')], db_index=True, max_length=64),
        ),
    ]
