# Generated by Django 5.1.7 on 2025-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_file', models.FileField(max_length=255, upload_to='videos/original/')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='videos/thumbnails/')),
                ('video_480p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/480p/')),
                ('video_720p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/720p/')),
                ('video_1080p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/1080p/')),
                ('hls_480p_manifest', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/hls/480p/')),
                ('hls_720p_manifest', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/hls/720p/')),
                ('hls_1080p_manifest', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/hls/1080p/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animation'), ('fantasy', 'Fantasy')], max_length=50)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
