services:
  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: app_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - redis
