# Generated by Django 5.2.12 on 2026-03-27 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idea_app', '0001_initial'),
        ('niche_app', '0004_add_research_retry_count'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, default='', upload_to='designs/assets/%Y/%m/')),
                ('file_url', models.URLField(blank=True, default='', max_length=2048)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('generated', 'Generated')], db_index=True, default='upload', max_length=20)),
                ('source_file_id', models.CharField(blank=True, default='', help_text='External file ID (Drive/OneDrive)', max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=2048)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='{width, height} in pixels')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('round', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_design_assets', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_assets', to='idea_app.idea')),
                ('niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_assets', to='niche_app.niche')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_assets', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveIntegerField(default=1)),
                ('brand_name', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('bullet_1', models.CharField(blank=True, default='', max_length=256)),
                ('bullet_2', models.CharField(blank=True, default='', max_length=256)),
                ('bullet_3', models.CharField(blank=True, default='', max_length=256)),
                ('bullet_4', models.CharField(blank=True, default='', max_length=256)),
                ('bullet_5', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('backend_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('generated_by', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('availability', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('publish_mode', models.CharField(choices=[('live', 'Live'), ('draft', 'Draft')], default='live', max_length=10)),
                ('language', models.CharField(default='en', max_length=5)),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Per-language translations: {lang: {title, bullets, description}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='publish_app.designasset')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='idea_app.idea')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='designasset',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_assets', to='publish_app.listing'),
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_snapshot', models.JSONField(blank=True, default=dict, help_text='Denormalized listing fields at queue time')),
                ('marketplace', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('asin', models.CharField(blank=True, default='', max_length=20)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_screenshot', models.URLField(blank=True, default='', max_length=2048)),
                ('retry_count', models.IntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_upload_jobs', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_jobs', to='publish_app.designasset')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_jobs', to='publish_app.listing')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_jobs', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductLifecycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(blank=True, default='', max_length=20)),
                ('marketplace', models.CharField(blank=True, default='', max_length=20)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('sales_units', models.IntegerField(blank=True, null=True)),
                ('sales_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_bsr', models.IntegerField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('reviews_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('round', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lifecycles', to='publish_app.designasset')),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lifecycles', to='idea_app.idea')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lifecycles', to='publish_app.listing')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lifecycles', to='niche_app.niche')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lifecycles', to='workspace_app.workspace')),
                ('upload_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lifecycles', to='publish_app.uploadjob')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(blank=True, default='', max_length=50)),
                ('product_types', models.JSONField(blank=True, default=list, help_text='List of product type keys (e.g. standard_tshirt, hoodie)')),
                ('fit_types', models.JSONField(blank=True, default=list, help_text='List of fit types (e.g. men, women, youth)')),
                ('colors', models.JSONField(blank=True, default=list, help_text='List of MBA color codes')),
                ('marketplaces', models.JSONField(blank=True, default=list, help_text='List of {marketplace, price, enabled} objects')),
                ('print_side', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], default='front', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_upload_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_templates', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_jobs', to='publish_app.uploadtemplate'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['workspace', 'status'], name='listing_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['idea'], name='listing_idea_idx'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['workspace', 'source'], name='designasset_ws_source_idx'),
        ),
        migrations.AddIndex(
            model_name='productlifecycle',
            index=models.Index(fields=['niche', 'round'], name='lifecycle_niche_round_idx'),
        ),
        migrations.AddIndex(
            model_name='productlifecycle',
            index=models.Index(fields=['workspace'], name='lifecycle_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadtemplate',
            index=models.Index(fields=['workspace'], name='uploadtpl_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadjob',
            index=models.Index(fields=['workspace', 'status'], name='uploadjob_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadjob',
            index=models.Index(fields=['listing'], name='uploadjob_listing_idx'),
        ),
    ]
