# Generated by Django 5.2.13 on 2026-04-17 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_app', '0001_initial'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_design_collections', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder. Null = root level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='publish_app.designcollection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_collections', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='designasset',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection folder this asset belongs to. Null = root.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='publish_app.designcollection'),
        ),
        migrations.AddIndex(
            model_name='designcollection',
            index=models.Index(fields=['workspace', 'parent'], name='collection_ws_parent_idx'),
        ),
    ]
