# Generated by Django 5.2.13 on 2026-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0005_idea_board_layout'),
        ('publish_app', '0002_add_design_collection_model'),
        ('workspace_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='marketplace_type',
            field=models.CharField(choices=[('global', 'Global'), ('mba', 'Merch by Amazon'), ('displate', 'Displate')], db_index=True, default='mba', help_text='Marketplace variant. Each (design, marketplace_type) pair is unique.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('design', 'marketplace_type'), name='listing_unique_design_marketplace'),
        ),
    ]
