# Generated by Django 5.2.13 on 2026-04-18 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_app', '0003_add_listing_marketplace_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProductConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace_type', models.CharField(choices=[('global', 'Global'), ('mba', 'Merch by Amazon'), ('displate', 'Displate')], db_index=True, default='mba', max_length=20)),
                ('product_types', models.JSONField(blank=True, default=list, help_text='List of product type keys (e.g. t_shirt, hoodie, tank_top).')),
                ('fit_types', models.JSONField(blank=True, default=list, help_text='List of fit types (e.g. men, women, youth).')),
                ('print_side', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], default='front', max_length=10)),
                ('colors', models.JSONField(blank=True, default=list, help_text='List of MBA color keys (validated against MBA_COLORS palette).')),
                ('marketplaces', models.JSONField(blank=True, default=list, help_text='List of {marketplace, price, enabled} entries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='publish_app.designasset')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['design', 'marketplace_type'], name='designcfg_design_mt_idx')],
                'constraints': [models.UniqueConstraint(fields=('design', 'marketplace_type'), name='design_product_config_unique')],
            },
        ),
    ]
