# Generated by Django 5.2.13 on 2026-04-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_app', '0004_designproductconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, this Listing is a reusable template (design must be NULL). Templates are excluded from idea/listing default querysets and surfaced via /api/listings/templates/.'),
        ),
    ]
