# Generated by Django 5.2.13 on 2026-04-19 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_app', '0005_listing_is_template'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtemplate',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, this template is the workspace default for its (workspace, marketplace_type) pair. Exactly one default per marketplace per workspace (enforced by partial unique index).'),
        ),
        migrations.AddField(
            model_name='uploadtemplate',
            name='marketplace_type',
            field=models.CharField(choices=[('global', 'Global'), ('mba', 'Merch by Amazon'), ('displate', 'Displate')], db_index=True, default='mba', help_text='Marketplace this template targets. Defaults map to MBA. Used together with `is_default` to pick a workspace default per marketplace.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='uploadtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('workspace', 'marketplace_type'), name='upload_template_single_default'),
        ),
    ]
