# Generated by Django 5.2.13 on 2026-04-24 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_app', '0013_listing_extend_global_displate_fields'),
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('mba', 'Merch by Amazon'), ('basic', 'Basic')], max_length=10)),
                ('format', models.CharField(choices=[('xlsx', 'XLSX (ZIP)'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('design_ids', models.JSONField(blank=True, default=list, help_text='Denormalized list of DesignAsset UUIDs at export time. Survives design deletion (EC-68).')),
                ('design_count', models.IntegerField(default=0, help_text='Pre-fan-out selection size.')),
                ('row_count', models.IntegerField(default=0, help_text='Post-fan-out XLSX row count. Equals design_count for Basic and CSV variants.')),
                ('filename', models.CharField(blank=True, default='', help_text='Filename as served in Content-Disposition.', max_length=200)),
                ('output_size_bytes', models.BigIntegerField(blank=True, help_text='ZIP/CSV byte size (AC-138).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_export_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='exportlog_ws_created_idx')],
            },
        ),
    ]
