# Generated by Django 5.2.13 on 2026-05-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0011_generation_modes_remix'),
        ('publish_app', '0014_exportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='design_origin',
            field=models.ForeignKey(blank=True, help_text='Source Design this asset was generated from via "Send to Listings" (PROJ-9 Phase O). Null = uploaded/imported asset or source Design was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_assets', to='design_app.design'),
        ),
    ]
