# Generated by Django 5.2.12 on 2026-03-12 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('data_entry', 'Data Entry'), ('deep_research', 'Deep Research'), ('niche_with_potential', 'Niche with Potential'), ('to_designer', 'To Designer'), ('upload', 'Upload'), ('start_ads', 'Start Ads'), ('pending', 'Pending'), ('winner', 'Winner'), ('loser', 'Loser'), ('archived', 'Archived')], db_index=True, default='data_entry', max_length=25)),
                ('potential_rating', models.CharField(blank=True, choices=[('good', 'Gut'), ('very_good', 'Sehr gut'), ('rejected', 'Rejected')], default=None, max_length=15, null=True)),
                ('research_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done')], default=None, max_length=10, null=True)),
                ('research_run_id', models.UUIDField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_niches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_niches', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niches', to='workspace_app.workspace')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='niche_ws_status_idx'), models.Index(fields=['workspace', 'status', 'position'], name='niche_ws_status_pos_idx')],
            },
        ),
    ]
