# Generated by Django 5.2.12 on 2026-03-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0003_add_niche_filter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='research_retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of research retries for this niche (max 3)'),
        ),
    ]
