# Generated by Django 5.2.12 on 2026-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0004_add_research_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='current_round',
            field=models.PositiveIntegerField(default=1, help_text='Current active round for the niche'),
        ),
    ]
