# Generated by Django 5.2.13 on 2026-04-25 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0006_add_collected_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NicheNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_niche_notes', to=settings.AUTH_USER_MODEL)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_collection', to='niche_app.niche')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
