# Generated by Django 5.2.14 on 2026-05-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0008_nichenote_source_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='builder_form_hints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
