# Generated by Django 5.2.14 on 2026-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche_app', '0009_niche_builder_form_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='best_of_mix_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
