"""Pydantic schemas for LLM structured output (with_structured_output)."""
from pydantic import BaseModel, Field


# ---------- Original Analysis (Graph 1, Node 1) ----------


class OriginalAnalysisSchema(BaseModel):
    """Structured output from analyzing the source slogan."""

    primary_pattern: str = Field(
        description="One of the 16 emotional patterns (e.g. 'IDENTITY DECLARATION').",
    )
    sentence_structure: str = Field(
        description="Structure type: Simple Declaration, Statement + Twist, Question + Answer, etc.",
    )
    formula_pattern: str = Field(
        description="Reusable template with [BRACKETS]=variables, CAPS=constants.",
    )
    power_words: list[str] = Field(
        description="Intensity amplifiers, boundary language, authority markers.",
    )
    signal_type: str = Field(
        description="SELF (declarative/inward) or OTHER (instructional/outward).",
    )
    element_count: int = Field(
        description="Number of distinct text elements in the slogan.",
    )
    tone: str = Field(
        description="Overall tone (e.g. Proud, Defiant, Humorous).",
    )
    energy: str = Field(
        description="Low / Medium / High.",
    )


# ---------- Niche Evaluation (Graph 1, Node 2) ----------


class SignalConversionSchema(BaseModel):
    """Signal conversion details for niche evaluation."""

    required: bool = Field(description="Whether signal conversion is needed.")
    direction: str = Field(
        default="",
        description="SELF->OTHER or OTHER->SELF, empty if not required.",
    )
    transformation_strategy: str = Field(
        default="",
        description="How to convert the signal.",
    )


class NicheEvaluationSchema(BaseModel):
    """Evaluation of a single target niche for slogan compatibility."""

    niche_id: str = Field(description="UUID of the target niche.")
    niche_name: str = Field(description="Name of the target niche.")
    approval_status: str = Field(description="APPROVED or REJECTED.")
    compatibility_score: int = Field(
        description="0-100 compatibility score. >=75 = APPROVED.",
    )
    signal_conversion: SignalConversionSchema
    rejection_reason: str = Field(
        default="",
        description="Reason for rejection, empty if approved.",
    )
    emotional_alignment: str = Field(
        description="How the niche's emotional reality aligns with the slogan.",
    )


class NicheEvaluationListSchema(BaseModel):
    """Wrapper for list of niche evaluations (with_structured_output requires a class)."""

    evaluations: list[NicheEvaluationSchema] = Field(
        description="List of niche evaluations.",
    )


# ---------- Product Validation (Graph 1, Node 3) ----------


class ValidatedProductSchema(BaseModel):
    """A validated reference product for slogan adaptation."""

    quality_gate: str = Field(description="PROCEED or REJECT.")
    slogan: str = Field(default="", description="Product slogan text.")
    pattern: str = Field(default="", description="Emotional pattern of the product.")
    formula: str = Field(default="", description="Adaptation formula.")
    energy: str = Field(default="", description="Low / Medium / High.")
    insider_terms: list[str] = Field(
        default_factory=list,
        description="Niche-specific terms.",
    )
    match_score: int = Field(default=0, description="0-100 match score.")


class ProductValidationResultSchema(BaseModel):
    """Result of product validation for a niche."""

    niche_id: str
    validated_products: list[ValidatedProductSchema]


# ---------- Slogan Adaptation (Graph 2, Node 1) ----------


class AdaptedSloganSchema(BaseModel):
    """A single adapted slogan generated by the adaptation engine."""

    slogan_text: str = Field(description="The adapted slogan text.")
    creative_modules_used: list[str] = Field(
        description="Creative techniques applied.",
    )
    emotional_archetype: str = Field(
        description="Fighter, Jester, Rebel, Sage, etc.",
    )
    buyer_voice_pattern: str = Field(
        description="How the buyer would voice this (e.g. 'HELL YEAH I...').",
    )
    stylistic_device: str = Field(
        description="Exaggeration, irony, contrast, etc.",
    )
    pattern_used: str = Field(
        description="Which of the 16 patterns was used.",
    )
    why_it_works: str = Field(
        description="Brief explanation of effectiveness.",
    )
    market_confidence: str = Field(
        description="High, Medium, or Low.",
    )
    signal_type: str = Field(
        description="SELF or OTHER.",
    )


class AdaptationOutputSchema(BaseModel):
    """Output from the adaptation engine -- 10 slogans per niche."""

    slogans: list[AdaptedSloganSchema] = Field(
        description="Exactly 10 adapted slogans: 5 SELF + 5 OTHER.",
    )


# ---------- Quality Check (Graph 2, Node 2) ----------


class QualityResultSchema(BaseModel):
    """Quality check result for a single slogan."""

    original_text: str
    corrected_text: str
    was_changed: bool
    change_reason: str = Field(
        default="",
        description="Reason for correction, empty if unchanged.",
    )
    signal_type: str = Field(description="Verified SELF or OTHER.")
    market_confidence: str = Field(description="Verified High, Medium, or Low.")


class QualityCheckOutputSchema(BaseModel):
    """Output from quality check -- all slogans validated."""

    results: list[QualityResultSchema]
