"""
PROJ-4 — User Profile & Billing: backend tests.

Covers task-list items 10 (profile + billing subtests):
  - PATCH /api/users/me/  — updates fields; email ignored; duplicate username → 400
  - POST /api/users/me/avatar/  — valid → 200; >2MB → 400; wrong type → 400
  - POST /api/auth/password/change/  — correct → 200; wrong → 400
  - GET /api/users/me/billing/  — new user → empty object, not 404
  - PUT /api/users/me/billing/  — invalid country → 400
"""

import io
import pytest
from django.urls import reverse
from rest_framework.test import APIClient
from rest_framework_simplejwt.tokens import RefreshToken

from user_auth_app.models import User, BillingProfile


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_user(email, password="TestPass123!", active=True, **kwargs):
    return User.objects.create_user(
        email=email,
        password=password,
        username=email,
        is_active=active,
        **kwargs,
    )


def auth_client(user):
    client = APIClient()
    token = str(RefreshToken.for_user(user).access_token)
    client.cookies["access_token"] = token
    return client


def _minimal_jpeg_bytes(size_bytes=100):
    """Return a valid JPEG byte stream generated by Pillow (1x1 white pixel)."""
    from PIL import Image as PilImage
    buf = io.BytesIO()
    img = PilImage.new("RGB", (1, 1), color=(255, 255, 255))
    img.save(buf, format="JPEG")
    return buf.getvalue()


# ---------------------------------------------------------------------------
# 8. PATCH /api/users/me/
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_patch_me_updates_allowed_fields():
    user = make_user("patchme@test.com", first_name="Old", last_name="Name")
    client = auth_client(user)
    url = reverse("user-profile")
    response = client.patch(
        url,
        {"first_name": "New", "last_name": "Name2", "username": "patchme_new"},
        format="json",
    )
    assert response.status_code == 200
    user.refresh_from_db()
    assert user.first_name == "New"
    assert user.last_name == "Name2"
    assert user.username == "patchme_new"


@pytest.mark.django_db
def test_patch_me_email_is_ignored():
    user = make_user("emailignored@test.com")
    original_email = user.email
    client = auth_client(user)
    url = reverse("user-profile")
    response = client.patch(url, {"email": "hacked@evil.com"}, format="json")
    assert response.status_code == 200
    user.refresh_from_db()
    assert user.email == original_email


@pytest.mark.django_db
def test_patch_me_duplicate_username_returns_400():
    user1 = make_user("dupuser1@test.com")
    user1.username = "taken_username"
    user1.save(update_fields=["username"])
    user2 = make_user("dupuser2@test.com")
    client = auth_client(user2)
    url = reverse("user-profile")
    response = client.patch(url, {"username": "taken_username"}, format="json")
    assert response.status_code == 400


@pytest.mark.django_db
def test_patch_me_unauthenticated_returns_401():
    client = APIClient()
    url = reverse("user-profile")
    response = client.patch(url, {"first_name": "X"}, format="json")
    assert response.status_code == 401


# ---------------------------------------------------------------------------
# 9. POST /api/users/me/avatar/
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_avatar_upload_valid_jpeg_returns_200(tmp_path, settings):
    settings.MEDIA_ROOT = str(tmp_path)
    user = make_user("avatarvalid@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")

    img_bytes = _minimal_jpeg_bytes(500)
    img_file = io.BytesIO(img_bytes)
    img_file.name = "avatar.jpg"

    response = client.post(url, {"avatar": img_file}, format="multipart")
    assert response.status_code == 200
    assert "avatar_url" in response.json()

    user.refresh_from_db()
    assert user.avatar  # stored on user model


@pytest.mark.django_db
def test_avatar_upload_too_large_returns_400(tmp_path, settings):
    settings.MEDIA_ROOT = str(tmp_path)
    user = make_user("avatarlarge@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")

    # Build a file > 2MB by creating a BytesIO with fake content_type checked by view
    large_data = b"\xff\xd8\xff\xe0" + b"\x00" * (2 * 1024 * 1024 + 1)
    large_file = io.BytesIO(large_data)
    large_file.name = "big.jpg"

    from django.core.files.uploadedfile import InMemoryUploadedFile
    uploaded = InMemoryUploadedFile(
        file=large_file,
        field_name="avatar",
        name="big.jpg",
        content_type="image/jpeg",
        size=len(large_data),
        charset=None,
    )

    response = client.post(url, {"avatar": uploaded}, format="multipart")
    assert response.status_code == 400
    assert "2 MB" in response.json()["detail"] or "large" in response.json()["detail"].lower()


@pytest.mark.django_db
def test_avatar_upload_wrong_type_returns_400(tmp_path, settings):
    settings.MEDIA_ROOT = str(tmp_path)
    user = make_user("avatartype@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")

    from django.core.files.uploadedfile import InMemoryUploadedFile
    pdf_file = InMemoryUploadedFile(
        file=io.BytesIO(b"%PDF-1.4 fake"),
        field_name="avatar",
        name="doc.pdf",
        content_type="application/pdf",
        size=13,
        charset=None,
    )
    response = client.post(url, {"avatar": pdf_file}, format="multipart")
    assert response.status_code == 400
    assert "type" in response.json()["detail"].lower() or "supported" in response.json()["detail"].lower()


@pytest.mark.django_db
def test_avatar_upload_no_file_returns_400():
    user = make_user("avatarnofile@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")
    response = client.post(url, {}, format="multipart")
    assert response.status_code == 400


# ---------------------------------------------------------------------------
# 10. POST /api/auth/password/change/
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_password_change_correct_password_returns_200():
    user = make_user("pwchange@test.com", password="OldPass123!")
    client = auth_client(user)
    url = reverse("password_change")
    response = client.post(
        url,
        {
            "current_password": "OldPass123!",
            "new_password": "NewPass456!",
            "confirm_password": "NewPass456!",
        },
        format="json",
    )
    assert response.status_code == 200
    # Cookie must be cleared (logout)
    assert "detail" in response.json()


@pytest.mark.django_db
def test_password_change_wrong_current_password_returns_400():
    user = make_user("pwwrong@test.com", password="CorrectPass123!")
    client = auth_client(user)
    url = reverse("password_change")
    response = client.post(
        url,
        {
            "current_password": "WrongPass999!",
            "new_password": "NewPass456!",
            "confirm_password": "NewPass456!",
        },
        format="json",
    )
    assert response.status_code == 400


@pytest.mark.django_db
def test_password_change_mismatched_new_passwords_returns_400():
    user = make_user("pwmismatch@test.com", password="OldPass123!")
    client = auth_client(user)
    url = reverse("password_change")
    response = client.post(
        url,
        {
            "current_password": "OldPass123!",
            "new_password": "NewPass456!",
            "confirm_password": "DifferentPass789!",
        },
        format="json",
    )
    assert response.status_code == 400


@pytest.mark.django_db
def test_password_change_unauthenticated_returns_401():
    client = APIClient()
    url = reverse("password_change")
    response = client.post(
        url,
        {
            "current_password": "any",
            "new_password": "NewPass456!",
            "confirm_password": "NewPass456!",
        },
        format="json",
    )
    assert response.status_code == 401


# ---------------------------------------------------------------------------
# 11. GET /api/users/me/billing/ — new user → empty object, not 404
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_billing_get_new_user_returns_200_not_404():
    user = make_user("billingnew@test.com")
    client = auth_client(user)
    url = reverse("user-billing")
    response = client.get(url)
    assert response.status_code == 200
    # BillingProfile auto-created with defaults
    data = response.json()
    assert "account_type" in data
    assert data["account_type"] == BillingProfile.AccountType.PERSONAL


@pytest.mark.django_db
def test_billing_get_creates_profile_only_once():
    user = make_user("billingonce@test.com")
    client = auth_client(user)
    url = reverse("user-billing")
    client.get(url)
    client.get(url)
    assert BillingProfile.objects.filter(user=user).count() == 1


# ---------------------------------------------------------------------------
# 12. PUT /api/users/me/billing/ — invalid country → 400
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_billing_put_invalid_country_returns_400():
    user = make_user("billingbadcountry@test.com")
    client = auth_client(user)
    url = reverse("user-billing")
    response = client.put(
        url,
        {"account_type": "personal", "country": "XX"},
        format="json",
    )
    assert response.status_code == 400


@pytest.mark.django_db
def test_billing_put_valid_data_returns_200():
    user = make_user("billingvalid@test.com")
    client = auth_client(user)
    url = reverse("user-billing")
    response = client.put(
        url,
        {
            "account_type": "business",
            "company_name": "Acme GmbH",
            "vat_number": "DE123456789",
            "address_line1": "Musterstraße 1",
            "city": "Berlin",
            "postal_code": "10115",
            "country": "DE",
        },
        format="json",
    )
    assert response.status_code == 200
    data = response.json()
    assert data["account_type"] == "business"
    assert data["country"] == "DE"
    assert data["vat_number"] == "DE123456789"


@pytest.mark.django_db
def test_billing_put_business_without_vat_is_allowed():
    """VAT is optional even for business type."""
    user = make_user("billingnovai@test.com")
    client = auth_client(user)
    url = reverse("user-billing")
    response = client.put(
        url,
        {"account_type": "business", "company_name": "No VAT Corp", "country": "US"},
        format="json",
    )
    assert response.status_code == 200


@pytest.mark.django_db
def test_billing_unauthenticated_returns_401():
    client = APIClient()
    url = reverse("user-billing")
    response = client.get(url)
    assert response.status_code == 401


# ---------------------------------------------------------------------------
# BUG-6 — Pillow magic-byte validation
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_rejects_fake_jpeg_with_png_content(tmp_path, settings):
    """File declared as image/jpeg but containing PNG bytes must be rejected."""
    settings.MEDIA_ROOT = str(tmp_path)
    user = make_user("fakejpeg@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")

    # Minimal 1x1 PNG bytes
    png_bytes = (
        b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
        b"\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc\xf8\x0f\x00"
        b"\x00\x01\x01\x00\x05\x18\xd8N\x00\x00\x00\x00IEND\xaeB`\x82"
    )

    from django.core.files.uploadedfile import InMemoryUploadedFile
    fake_jpeg = InMemoryUploadedFile(
        file=io.BytesIO(png_bytes),
        field_name="avatar",
        name="avatar.jpg",
        content_type="image/jpeg",  # lying about content type
        size=len(png_bytes),
        charset=None,
    )
    response = client.post(url, {"avatar": fake_jpeg}, format="multipart")
    assert response.status_code == 400
    assert "match" in response.json()["detail"].lower() or "invalid" in response.json()["detail"].lower()


@pytest.mark.django_db
def test_rejects_non_image_binary(tmp_path, settings):
    """Binary file that is not an image at all must be rejected."""
    settings.MEDIA_ROOT = str(tmp_path)
    user = make_user("nonimage@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")

    from django.core.files.uploadedfile import InMemoryUploadedFile
    garbage = InMemoryUploadedFile(
        file=io.BytesIO(b"\x00\x01\x02\x03this is not an image at all!!!"),
        field_name="avatar",
        name="avatar.jpg",
        content_type="image/jpeg",
        size=32,
        charset=None,
    )
    response = client.post(url, {"avatar": garbage}, format="multipart")
    assert response.status_code == 400
    assert "invalid" in response.json()["detail"].lower()


# ---------------------------------------------------------------------------
# BUG-7 — Avatar stores relative path
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_avatar_stores_relative_path(tmp_path, settings):
    """After upload, user.avatar must be a relative /media/... path, not an absolute URL."""
    settings.MEDIA_ROOT = str(tmp_path)
    user = make_user("avatarrel@test.com")
    client = auth_client(user)
    url = reverse("user-avatar")

    img_bytes = _minimal_jpeg_bytes(500)
    img_file = io.BytesIO(img_bytes)
    img_file.name = "avatar.jpg"

    response = client.post(url, {"avatar": img_file}, format="multipart")
    assert response.status_code == 200

    user.refresh_from_db()
    assert user.avatar.startswith("/media/"), (
        f"Expected relative /media/... path, got: {user.avatar}"
    )
    assert not user.avatar.startswith("http"), (
        f"avatar field must not store absolute URL, got: {user.avatar}"
    )
